### ISSUE TITLE
convert.py doesn't work

### ISSUE THREAD

**Issue by marcin-przywoski** [Kewee123/snapchatMemories#1]
Checked with a few Python versions but the convert script does not work. It doesn't throw an error either. I'm not seeing .json file created aswell. How long it should run before it will appear?

**Comment by Kewee123** [comment]
Hi, what errors are you running into?

I was going to specify more what programs/etc were needed, but didn't have the time yet.

**Comment by marcin-przywoski** [comment]
Actually none, the script opens up but I'm not seeing any kind of response. I kept it open for about an hour and it closed itself. Still no expected .json file from what I see. Windows 10 x64 here.

**Comment by marcin-przywoski** [comment]
Tried it on Python 3.6 / 3.7 /3.8. Are there any additional libraries / programs needed? I tried to ensure everything is on point in VS.

**Comment by Kewee123** [comment]
I'll take a run through from scratch on another Windows laptop and document the steps from there and hopefully you'll be able to get it to run.

Thanks for the heads up.

**Comment by Kewee123** [comment]
I updated the readme.

You will need Python3.8 with requests library installed and the newest file of snapchat memories

Memories_history

**Comment by marcin-przywoski** [comment]
I had it installed already and still doesn't work :( You mean downloading it once again? I have requested snapchat files yesterday so they are not so old.

**Comment by marcin-przywoski** [comment]
Double checked, for some reason I'm getting unresolved import for requests even though I have it installed....hmmmm

**Comment by Kewee123** [comment]
It might be using the older version of python.

I ran into that issue and had to reinstall it for 3.8 and then make sure to enable path and select the right interpreter on VSCode

**Comment by marcin-przywoski** [comment]
I downloaded the newest from their website and it was the same :/ From where I should download it?

**Comment by marcin-przywoski** [comment]
I copied requests lib to the 3.8 directory in AppData\Local and then run it from PS  directly instead of alias
but same thing happens...no response

**Comment by marcin-przywoski** [comment]
Which interpreter is right to use?

**Comment by Kewee123** [comment]
Well
I usually use VSC, and did a fresh install of python 3.8 on my windows 10 computer.
When I ran py -v in VSC, it was able to find python3.8
After that I did pip install requests and followed the following steps.

**Comment by marcin-przywoski** [comment]
I did the same but it's still not working...it detects the correct location and version VSC is set to correct interpreter aswell but it still doesn't work for some reason

**Comment by Kewee123** [comment]
It still isn't able to detect the request module?
